//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBP.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class BankTransferPolicy
    {
        public int Id { get; set; }
        public int BankTransferId { get; set; }
        public int TacticalRowId { get; set; }
    
        public virtual BankTransfer BankTransfer { get; set; }
        public virtual TacticalRow TacticalRow { get; set; }
    }
}
