//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBP.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cancellation
    {
        public int Id { get; set; }
        public int TacticalRowId { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<bool> PremioAccantonatoVita { get; set; }
        public Nullable<bool> PremioRimborsatoVita { get; set; }
        public Nullable<System.DateTime> DataAccantonatoVita { get; set; }
        public Nullable<bool> PremioAccantonatoDanni { get; set; }
        public Nullable<bool> PremioRimborsatoDanni { get; set; }
        public Nullable<System.DateTime> DataAccontonatoDanni { get; set; }
        public Nullable<int> BankTransferId { get; set; }
        public Nullable<System.DateTime> DataDistintaVita { get; set; }
        public Nullable<System.DateTime> DataDistintaDanni { get; set; }
        public Nullable<System.DateTime> DataValutaVita { get; set; }
        public Nullable<System.DateTime> DataValutaDanni { get; set; }
    
        public virtual BankTransfer BankTransfer { get; set; }
        public virtual TacticalRow TacticalRow { get; set; }
    }
}
