//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBP.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class GeneralInfo
    {
        public int Id { get; set; }
        public string LastImportedFileName { get; set; }
        public Nullable<System.DateTime> LastImportedDate { get; set; }
        public string LastEAPImportedFileName { get; set; }
        public Nullable<System.DateTime> LastEAPImportedDate { get; set; }
        public string LastRecessiImportedFileName { get; set; }
        public Nullable<System.DateTime> LastRecessiImportedDate { get; set; }
    }
}
