//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBP.DataLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class TacticalRow
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TacticalRow()
        {
            this.BankTransferPolicies = new HashSet<BankTransferPolicy>();
            this.Beneficiaries = new HashSet<Beneficiary>();
            this.Cancellations = new HashSet<Cancellation>();
        }
    
        public int Id { get; set; }
        public int PolicyNumber { get; set; }
        public string Surname { get; set; }
        public string FirstName { get; set; }
        public System.DateTime Birth { get; set; }
        public int CalculatedAge { get; set; }
        public int Sex { get; set; }
        public string ZipCode { get; set; }
        public string Location { get; set; }
        public string Street { get; set; }
        public string TransactionType { get; set; }
        public string Tariff { get; set; }
        public Nullable<int> Duration { get; set; }
        public Nullable<System.DateTime> DateOfCancellation { get; set; }
        public Nullable<System.DateTime> DateOfSignature { get; set; }
        public Nullable<System.DateTime> ExpirationDate { get; set; }
        public Nullable<double> InsuredSum { get; set; }
        public double PremioLordo { get; set; }
        public Nullable<double> Tassi { get; set; }
        public Nullable<double> PremioNetto { get; set; }
        public Nullable<double> Commissioni { get; set; }
        public Nullable<double> PremioVita { get; set; }
        public Nullable<double> CommissioniVita { get; set; }
        public Nullable<double> PremioLordoDanni { get; set; }
        public Nullable<double> TassiDanni { get; set; }
        public Nullable<double> PremioNettoDanni { get; set; }
        public Nullable<double> CommissioniDanni { get; set; }
        public Nullable<double> InsuredRate { get; set; }
        public Nullable<double> ImportoEstinzione { get; set; }
        public Nullable<double> CapitaleResiduo { get; set; }
        public Nullable<System.DateTime> DataRimborso { get; set; }
        public string Provincia { get; set; }
        public string Iban { get; set; }
        public Nullable<System.DateTime> DateOfCancellation2 { get; set; }
        public Nullable<System.DateTime> DateOfCancellation3 { get; set; }
        public Nullable<double> ImportoEstinzione2 { get; set; }
        public Nullable<System.DateTime> ExpirationDate2 { get; set; }
        public Nullable<double> DebitoResiduo { get; set; }
        public string HE { get; set; }
        public string CognomeCoIntestario { get; set; }
        public string NomeCoIntestatario { get; set; }
        public Nullable<bool> RichiestaSottoscrittore { get; set; }
        public Nullable<bool> CartaIdentita { get; set; }
        public Nullable<bool> CodiceFiscale { get; set; }
        public Nullable<System.DateTime> DataLavorazione { get; set; }
        public Nullable<bool> Cointestatario { get; set; }
        public Nullable<bool> CointestatarioCartaIdentita { get; set; }
        public string NominativoAderente { get; set; }
        public string CodiceFiscaleAderente { get; set; }
        public Nullable<double> DebitoResiduoIniziale { get; set; }
        public Nullable<System.DateTime> CointestatarioDataNascita { get; set; }
        public bool RecessoDisdettaCompleto { get; set; }
        public bool Santander { get; set; }
        public string Targa { get; set; }
        public string Telaio { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BankTransferPolicy> BankTransferPolicies { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Beneficiary> Beneficiaries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Cancellation> Cancellations { get; set; }
    }
}
